### ISSUE TITLE
I can't run the code.

### ISSUE THREAD

**Issue by mstf01** [bjlli/DMD-for-STM32#1]
Hello,
First of all, thank you for this project.
I am using stm32f103c8t6 but I could not run the code. I compile it and upload it to the microprocessor and I make the P10 panel connection but it does not work.

I think the problem may be the connection.
What kind of connection did you make? can you share.

**Comment by bjlli** [comment]
Hello!
You're welcome :)
I ran this library on a Black Pill Board (stm32f401ccu6), so in my case I used the following configuration:

STM pins| Interface | P10 pins
PA8 | GPIO | OE
PB13 | GPIO | A
PB12 | GPIO | B
PB10 | SCK | CLK
PB14 | GPIO | SCLK
PB15 | MOSI | DATA

You will probably have to adapt the pins to your case, but remember to keep the interfaces, this implementation requires a spi.

Good luck!

**Comment by mstf01** [comment]
Hello again and thank you again.

I ran the code but when I use the clear screen function the P10 screen blinks visibly, how can I solve this?

I changed the SPI scan frequency with the stm32 timer settings but it didn't fix it.

**Comment by bjlli** [comment]
Hi, 

Which clock frequency of spi are using? Have you tried to write a pixel without the toggle mode? 

For example, if you write a single pixel and you can visibly see it blinking you should make the spi faster. You'll need to test the frequencies to see which one is visibly fine.

**Comment by mstf01** [comment]
I use 18 MBit/s spi frequency, I don't use toggle mode, I use the clear function first and then I write something on the screen, when I use it this way, the screen seems to turn off and on very fast, I can notice this by eye, but when I don't use the clear function, there is no such problem, but some pixels remain on the screen.

**Comment by bjlli** [comment]
You shouldn't clear the screen every time you write. You need to set a timer interrupt to scan the screen and clear it at the start of the application.

The pixels that remain on the screen are probably due to previous information that has been sent to the display. For example, suppose you write "hello" and then write "hi", you are only changing the first two characters in the display's RAM mirror, the rest of the memory allocated to the display remains the same. Take a look at the c memset function, which can help you with this problem.
